---
- name: Configure VM2 — basic tools
  hosts: all
  become: true
  roles:
    - role: vm2_basic
      when: vm_role == "vm2"

- name: Configure VM3 — firewall
  hosts: all
  become: true
  roles:
    - role: vm3_db_secure
      when: vm_role == "vm3"

- name: Configure VM4 — AI basic tools
  hosts: all
  become: true
  roles:
    - role: vm4_ai_basic
      when: vm_role == "vm4"