server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri; # Redirection vers HTTPS
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    location / {
    proxy_pass http://frontend:80; # Points to the prod frontend Nginx
    # (You can also remove the Vite HMR websocket stuff here since prod doesn't use it)
    }

    location /api {
        proxy_pass http://backend:3000; # Points to the prod backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}