---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - curl
      - git
      - net-tools
      - ufw
      - docker.io
      - docker-compose
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: true

- name: Create VM3 docker-compose.yml
  copy:
    dest: /home/vagrant/docker-compose.yml
    owner: vagrant
    group: vagrant
    mode: "0644"
    content: |
      services:
        postgres:
          image: postgres:16-alpine
          container_name: postgres-db-container
          restart: unless-stopped
          env_file:
            - .env
          ports:
            - "192.168.56.12:5432:5432"
          volumes:
            - postgres_data:/var/lib/postgresql/data

      volumes:
        postgres_data:

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow PostgreSQL only from VM2
  ufw:
    rule: allow
    src: "192.168.56.11"
    port: "5432"
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow Node Exporter (Prometheus)
  ufw:
    rule: allow
    port: "9100"
    proto: tcp    

- name: Copy .env to VM
  copy:
    src: /vagrant/.env
    dest: /home/vagrant/.env
    owner: vagrant
    group: vagrant
    mode: "0644"    

- name: Recreate clean Docker stack
  shell: |
    docker-compose down
    docker-compose up -d --force-recreate --remove-orphans
  args:
    chdir: /home/vagrant
    
- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Start Node Exporter
  service:
    name: prometheus-node-exporter
    enabled: yes
    state: started