---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - curl
      - git
      - net-tools
      - docker.io
      - docker-compose
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: true

- name: Create app directory
  file:
    path: /opt/app
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /opt/app/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Copy Prometheus configuration
  copy:
    src: prometheus.yml
    dest: /opt/app/prometheus.yml
    mode: "0644"

- name: Copy nginx configuration
  copy:
    src: nginx.conf
    dest: /opt/app/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: Copy .env to VM
  copy:
    src: /vagrant/.env
    dest: /opt/app/.env
    owner: root
    group: root
    mode: "0600"

- name: Pull latest app images
  command: docker-compose pull
  args:
    chdir: /opt/app

- name: Ensure app stack is running
  command: docker-compose up -d --remove-orphans
  args:
    chdir: /opt/app

- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Start Node Exporter
  service:
    name: prometheus-node-exporter
    enabled: yes
    state: started

- name: Run cAdvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    state: started
    restart_policy: unless-stopped
    privileged: true
    command:
      - --docker_only=true
      - --disable_root_cgroup_stats=true
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

- name: Run nginx exporter
  community.docker.docker_container:
    name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:latest
    restart_policy: unless-stopped
    network_mode: host
    command:
      - "-nginx.scrape-uri=http://127.0.0.1:80/stub_status"
