services:
  ai:
    build:
      context: ../../ai
      target: development
    volumes:
      - ../../ai/scripts:/app/scripts
      - ../../ai/data:/app/data
      - ../../ai/models:/app/models:ro
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ENV=development
