services:
  ai:
    build:
      context: ../../ai
      target: development-ai
    volumes:
      - ../../ai/scripts:/app/scripts
    #  - ../../ai/src:/app/src   : le dossier src n'existe pas !
      - ../../ai/data:/app/data
      - ../../ai/models:/app/models  
    ports:
      - "8000:8000"