services:
  backend:
    container_name: back-app-container
    ports:
      - "4001:4001"
    build:
      context: ../../backend
    env_file:
      - ../../backend/.env
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: frontend-container
    build:
      context: ../../frontend
      #target: development # pour nginx
    # ports:
    #   - "5173:5173"  gerer au niveau de nginx pour le reverse proxy
    depends_on:
      - backend
  db:
    image: postgres:16-alpine
    container_name: postgres-db-container
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  ai:
    container_name: ai-container
    build:
      context: ../../ai
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    container_name: nginx-proxy
    build:
      context: ../../infrastructure/nginx
    ports:
      - "80:80"
      - "443:443" # On expose le port 443 pour HTTPS
    volumes:
      - nginx-certs:/etc/nginx/ssl # Volume pour garder les certs
    depends_on:
      - frontend
      - backend


volumes:
  postgres-db:
  nginx-certs: # Volume pour stocker les certificats TLS de Nginx
