services:
  cadvisor:
   image: gcr.io/cadvisor/cadvisor:latest
   container_name: cadvisor
   restart: unless-stopped
   ports:
      - "8081:8080"
   volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
   privileged: true
  backend:
    container_name: back-app-container
    build:
      context: ../../backend
    env_file:
      - ../../backend/.env
    expose:
      - "3000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend-container
    build:
      context: ../../frontend
    expose:
      - "8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: postgres-db-container
    restart: always
    env_file:
      - ../../backend/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    expose:
      - "5432"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  ai:
    container_name: ai-container
    build:
      context: ../../ai
    expose:
      - "8000"
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined

  nginx:
    container_name: nginx-proxy
    build:
      context: ../../infrastructure/nginx
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - nginx-certs:/etc/nginx/ssl
<<<<<<< HEAD
    security_opt:
      - no-new-privileges:true
=======
    cap_drop:
      - ALL
>>>>>>> frontend-portfolio
    depends_on:
      - frontend
      - backend

volumes:
  postgres-db:
  nginx-certs: